#!/usr/bin/python

import os
import shutil

# List of files to be ignored by the script.
ignored_files = ['README.md', 'setup']


def main():
  dstDir = os.environ['HOME']
  srcDir = os.getcwd()
  src = os.listdir(srcDir)
  dst = os.listdir(dstDir)

  print "Source: " + srcDir
  print "Destination: " + dstDir

  for file in src:
    if file not in ignored_files and not file.startswith('.'):

      # Delete the file if it's already in the destination to overwrite.
      if ('.%s' % file) in dst:
        print "Removing old copy of: .%s" % file

        try:
          os.remove(dstDir + '/.%s' % file)
        except OSError:
          shutil.rmtree(dstDir + '/.%s' % file)

      print "Creating symlink of file: .%s" % file
      os.symlink('%s/%s' % (srcDir, file), '%s/.%s' % (dstDir, file))

  return

if __name__ == '__main__':
  main()
